

    <a href="#" id="back-to-top">&uarr;</a>
    <!-- Footer -->
	<footer class="pt-5 bg-dark">
		<div class="container">
			<div class="row">
				<div class="col-lg-4">
					<h3 class="footer-title" >CONTATTI</h3>
					<p class="m-0 text-white"><strong>CST - DiathesisLab</strong><br>Via Salvecchio 19,  24129 Bergamo</p>
					<p class="m-0 text-white"><i class="fas fa-home"></i> <a href="https://www.unibg.it/ricerca/strutture-ricerca/centri-ateneo/cst/diathesis-lab" target="_blank">http://www.unibg.it/diathesis</a><br>
					<i class="far fa-envelope"></i> <a href="">diathesis@unibg.it</a>
					</p>
						
					</ul>
				</div>
				<div class="col-lg-4">
					<h3 class="footer-title" >MENU</h3>
					<ul class="list-unstyled row footer-menu">
						<li class="list-item col-5 py-1"><a href="index.php">Home</a></li>
						<li class="list-item col-5 py-1"><a href="partecipa.php">Partecipa</a></li>
						<li class="list-item col-5 py-1"><a href="progetto.php">Il Progetto</a></li>
						<li class="list-item col-5 py-1"><a href="stats.php">Statistiche</a></li>
						<li class="list-item col-5 py-1"><a href="calendario.php">Calendario</a></li>
						<li class="list-item col-5 py-1"><a href="team.php">Team</a></li>
						<li class="list-item col-5 py-1"><a href="privacy-policy.php">Privacy Policy</a></li>
						<li class="list-item col-5 py-1"><a href="cookie-policy.php">Cookie Policy</a></li>
					</ul>  
				</div>
				<div class="col-lg-4">
					<h3 class="footer-title" >UNIBG</h3>
					<img src="img/LogoFooter.png" height="85">
 
				</div>
				  
				 
				  
			</div>
		</div>
		<div class="text-center">
			<div class="col-12">
					<ul class="list-inline footer-social">
						<li>
							<a href="#"><i class="fab fa-facebook-f fa-fw fa-2x"></i></a>
							<a href="#"><i class="fab fa-instagram fa-fw fa-2x"></i></a>
							<a href="#"><i class="fab fa-twitter fa-fw fa-2x"></i></a>
							<a href="#"><i class="fab fa-youtube fa-fw fa-2x"></i></a>
						</li>
					</ul>
			</div>
		</div>
		<hr class="small">
		<div class="container copyright">
			<p class="m-0 text-center text-white">&copy; 2020 Università degli Studi di Bergamo</p>
		</div>

	</footer>
	<!-- START Bootstrap-Cookie-Alert -->
	<div class="alert text-center cookiealert" role="alert">
		Questo sito utilizza cookie tecnici, propri e di terze parti.&nbsp;Proseguendo la navigazione del sito o confermando tramite il tasto "Accetto" ne accetti l'utilizzo. 
		<a href="cookie-policy.php" target="_blank">Se vuoi saperne di più</a>
		<button type="button" class="btn btn-primary btn-sm acceptcookies" aria-label="Close">
			Accetto
		</button>
	</div>
	<!-- END Bootstrap-Cookie-Alert -->
